### ISSUE TITLE
Is Queries-Doctrine necessary?

### ISSUE THREAD

**Issue by simPod** [UselessSoft/queries-bundle#1]
Shouldn't there be a standalone bundle for https://github.com/UselessSoft/queries and https://github.com/UselessSoft/queries-doctrine each?

Eg. at our project, we dont need doctrine lib.

**Comment by simPod** [comment]
:neckbeard:

**Comment by Majkl578** [comment]
There is (in)direct dependency in services definition: https://github.com/UselessSoft/queries-bundle/blob/master/src/Resources/config/services.yaml#L28
The dependency could be made optional (moved to suggests), but the above would have to be registered conditionally too.
